### ISSUE TITLE
¿Traducir los ejemplos de código?

### ISSUE THREAD

**Issue by mirubiri** [mirubiri/El-Lenguaje-de-Programacion-Swift#1]
¿Debería traducir el código utilizado en los ejemplos?

**Comment by Lynx901** [comment]
Yo creo que no, no es algo tan necesario y realmente se entienden bastante bien, yo le daría más prioridad al texto plano. Por cierto, me gustaría contribuir a la traducción, me he descargado OmegaT y eso, ¿cómo podría ayudar?

**Comment by mirubiri** [comment]
Yo soy de tu misma opinión, aunque hay veces durante la traducción que se hace referencia a los ejemplos y a veces quedaría bien tenerlos traducidos (no ocurre mucho)

Sobre lo de OmegaT es fácil, en el directorio OEBPS/Text, se encuentran los archivos que hay que traducir. En OmegaT solo tienes que indicar que el origen y destino de la traducción se encuentra en esa carpeta. De todas formas, creo que lo mejor va a ser que integre en GitHub el proyecto con los archivos que yo he generado con OmegaT, ya que utiliza memoria de traducción y señala como se han traducido anteriormente algunos términos. Cuando vuelva mañana a casa preparo el proyecto y lo subo configurado con todo lo necesario.

**Comment by Lynx901** [comment]
Sobre las referencias al código, creo que también se deben de dejar tal cual por el simple hecho de mantener un poco la integridad del código y que haya los menos problemas, para que el lector tenga menos problemas a la hora de trabajar con los programas y de buscar cosas en internet relacionadas con ellos.

En cuanto tengas preparado todo empezaré a trastear con OmegaT, que es la primera vez que lo uso pero tiene buena pinta. ¡Gracias!

**Comment by mirubiri** [comment]
Esa es la mejor razón para dejarlos como están.
Gracias a ti !

**Comment by mirubiri** [comment]
Cierro el asunto.
