### ISSUE TITLE
Shorthand = Forma abreviada

### ISSUE THREAD

**Issue by mirubiri** [mirubiri/El-Lenguaje-de-Programacion-Swift#10]
Yo hasta ahora he traducido "shorthand" como "abreviatura" o "abreviación", pero quizá deberíamos traducirla como "forma abreviada" o "abreviada", creo que suena más natural.

"The expression a += 2is shorthand for a = a + 2"
"La expresión a += 2 es la abreviatura/abreviación de a = a + 2"

__"La expresión a += 2 es la forma abreviada de a = a + 2"__

**Comment by Lynx901** [comment]
Madre mía, infinitas gracias xD He tenido que traducir "shorthand" muchas veces esta mañana y siempre ponía "abreviatura" pero me sonaba tan forzado, tan artificial que no me gustaba, pero no conseguía encontrar otra expresión adecuada. Me parece una traducción genial la que propones.

**Comment by mirubiri** [comment]
Jajaja, bueno cuando algo te suene mal, tu ponlo aquí y lo hablamos, es mejor que dejarlo pasar.

**Comment by mirubiri** [comment]
Cierro también.
