### ISSUE TITLE
Hashable = que impementa el protocolo Hashable

### ISSUE THREAD

**Issue by Lynx901** [mirubiri/El-Lenguaje-de-Programacion-Swift#12]
> ### Hash Values for Set Types
> A type must be <e0>hashable</e0> in order to be stored in a set—that is, the type must provide a way to compute a <e1>hash value</e1> for itself.
> A hash value is an <c2>Int</c2> value that is the same for all objects that compare equally, such that if <c3>a == b</c3>, it follows that <c4>a.hashValue == b.hashValue</c4>.

A lo largo del apartado se vuelve a usar algunas veces el término "hashable" para indicar que un tipo tiene propiedades de hash. He buscado traducciones pero no encuentro nada. Propongo "españolizarlo" y hacer "hashable" = **hasheable** aunque suene algo vulgar xD

**Comment by mirubiri** [comment]
Quizá quede mejor traducir "hasheable" como "transformable/transformado/convertible/convertido/ interpretable/ interpretado " en un/como hash" o similares...



Enviado desde mi iPhone

**Comment by Lynx901** [comment]
Aún así creo que no capta el significado exacto de la palabra. Tampoco sabría decir exactamente cuál es ese significado, pero no lo relaciono con "transformable en un hash" o algo así...

**Comment by mirubiri** [comment]
Vale, he leído el contexto y Hashable es un protocolo de Swift. Lo que dice es que un tipo debe implementar el protocolo Hashable para poder ser incluido en un Set, así que la traducción sería:

"Un tipo debe __implementar el protocolo Hashable__ para que pueda ser almacenado en un set --esto significa, que el tipo debe proporcionar una forma de __calcular__ su propio valor hash.

Te marco la palabra __calcular__ por que he visto que la has traducido como "computar" al traducir esto.

¿Así se entiende mejor no?

**Comment by Lynx901** [comment]
Ambas cosas me parecen muy correctas, sobre todo lo de **implementar el protocolo Hashable**. Es largo pero creo que mantiene el significado.

**Comment by mirubiri** [comment]
Más adelante en la traducción hablan del protocolo Hashable, así que vamos por el buen camino
