### ISSUE TITLE
written as

### ISSUE THREAD

**Issue by mirubiri** [mirubiri/El-Lenguaje-de-Programacion-Swift#13]
> Daniel modificó por última vez la traducción el 20-jun-2016 a las 12:42:31
> The <c0>shoppingList</c0> variable is declared as “an array of string values”, written as <c1>[String]</c1>.
> La variable <c0>shoppingList</c0> se declara como "un array de valores string", __escrita como__ <c1>[String]</c1>.<segmento 2171>

Ese __escrita como__ creo que hay que traducirlo como __al escribir__ , si no, no tiene sentido, creo que yo también lo he puesto mal en anteriores traducciones.

**Comment by Lynx901** [comment]
En este caso diría que el sentido es que la variable "se escribe con el tipo [String]", por lo que considero que **escrita como**, porque no está "escribiendo String", si no que la variable se ha escrito como un String, ¿me explico?

**Comment by mirubiri** [comment]
El ejemplo es:
```
shoppingList :[String] = ["xxx","yyy","zzz"]
```

Lo que dice el párrafo es que una vez declarada la variable como [String], solo puedes introducir valores de tipo String en el array.

Yo lo que entiendo es que La variable shoppingList se ha declarado como "un array de valores string", por el hecho de escribir :[String]

**Comment by Lynx901** [comment]
Visto así... puede ser, la verdad xD

**Comment by mirubiri** [comment]
Perfecto entonces, otro asunto menos :wink:
