### ISSUE TITLE
infer = deducir

### ISSUE THREAD

**Issue by mirubiri** [mirubiri/El-Lenguaje-de-Programacion-Swift#14]
> Daniel modificó por última vez la traducción el 20-jun-2016 a las 12:44:10
> Because all values in the array literal are of the same type, Swift can infer that <c0>[String]</c0> is the correct type to use for the <c1>shoppingList</c1> variable.
> Como todos los valores en un literal de array son del mismo tipo, Swift puede inferir que <c0>[String]</c0> es el correcto para la variable <c1>shoppingList</c1>.<segmento 2181>

Aquí hay que tener cuidado con la traducción por que puede cambiar el significado:

Como todos los valores en __el__ literal de array son del mismo tipo, Swift puede __deducir__ que [String] es el __tipo__ __adecuado__ __a utilizar__ para la variable shoppingList.

__correct__ es muy común traducirlo demasiado rápido. (barbarismo)

:stuck_out_tongue_winking_eye:

**Comment by Lynx901** [comment]
Me parece muy bien el usar **deducir** en lugar de **inferir**. Es un significado más concreto y común. Si he usado **inferir** es por la costumbre al hablar.

En cuanto al correct, si consideramos que "[String]" es "un tipo de valor", decir que **[String] es el _(tipo)_ correcto** no lo veo mal, aunque quizá **adecuado** sea más _adecuado_ 😜

**Comment by mirubiri** [comment]
Si, quizá en este caso, tanto "adecuado", como "correcto", nos sirvan. Lo cierro que esto ya está resuelto.
