### ISSUE TITLE
Use = Utilize

### ISSUE THREAD

**Issue by mirubiri** [mirubiri/El-Lenguaje-de-Programacion-Swift#15]
> Daniel modificó por última vez la traducción el 20-jun-2016 a las 12:45:25
> Use the Boolean <c0>isEmpty</c0> property as a shortcut for checking whether the <c1>count</c1> property is equal to <c2>0</c2>:
> Use la propiedad Booleana <c0>isEmpty</c0> como una forma abreviada para comprobar si la propiedad <c1>count</c1> es igual a <c2>0</c2>:

Creo que queda mejor usar la palabra "Utilice" que "Use" en este tipo de frases. (y hay unas cuantas)

**Comment by mirubiri** [comment]
Por cierto, en este caso la traducción de shortcut, queda mejor asi:

Utilice la propiedad booleana isEmpty como forma rápida de comprobar si la propiedad count es igual a 0

(notar las minúsculas en booleana)

**Comment by Lynx901** [comment]
La verdad es que el "use" queda muy raro, pero también pasa en cosas como "Note that..."  que he traducido como "Dése cuenta que...". El lenguaje del uso formal es un gran extraño que hay que aprender a domar con cosas como **utilice** en lugar de **use**.

**Comment by mirubiri** [comment]
El "Note that" yo creo que lo he traducido como "Tenga en cuenta" casi siempre.

**Comment by Lynx901** [comment]
Ooooh, **tenga en cuenta** me gusta mucho más que **dése cuenta**. Punto para ti xDD

**Comment by mirubiri** [comment]
Solucionado esto entonces
