### ISSUE TITLE
Traducción peligrosa

### ISSUE THREAD

**Issue by mirubiri** [mirubiri/El-Lenguaje-de-Programacion-Swift#16]
> Daniel modificó por última vez la traducción el 20-jun-2016 a las 12:47:32
> Retrieve a value from the array by using <e0>subscript syntax</e0>, passing the index of the value you want to retrieve within square brackets immediately after the name of the array:
> Obtenga el valor de un array usando <e0>sintaxis de subscript</e0>, pasando el índice del valor que desea obtener entre corchetes inmediatamente después del nombre del array:<segmento 2203>

"El valor de un array", no es lo mismo que "un valor de un array".
En este caso queda mejor "Recupere un valor de un array...."

**Comment by Lynx901** [comment]
Totalmente de acuerdo. No he estado muy fino esta mañana...

**Comment by mirubiri** [comment]
Jajaja, no te preocupes, cuando pasas demasiado tiempo traduciendo sin descansar, ocurre mucho. Para eso estamos, para estar atentos a lo que hace el otro. 😉
