### ISSUE TITLE
Otra traducción rara

### ISSUE THREAD

**Issue by mirubiri** [mirubiri/El-Lenguaje-de-Programacion-Swift#17]
> Daniel modificó por última vez la traducción el 20-jun-2016 a las 12:48:49
> You can use subscript syntax to change an existing value at a given index:
> Puede usar sintaxis de subscript para cambiar un valor existente a un índice dado:<segmento 2209>

Esto se traduce mejor como: Puede utilizar la sintáxis de subscript, para cambiar un valor existente que se encuentra en un índice dado:

**Comment by Lynx901** [comment]
De nuevo el uso de **utilizar** sobre **usar**, que lo he comentado en el otro issue. El resto ha sido fallo de no leer la frase tras traducirla...

**Comment by mirubiri** [comment]
Cierro este y lo hablamos en #15
