### ISSUE TITLE
range = rango

### ISSUE THREAD

**Issue by mirubiri** [mirubiri/El-Lenguaje-de-Programacion-Swift#19]
Range = rango es otro barbarismo. La traducción correcta aquí creo que debería ser "intervalo"

**Comment by Lynx901** [comment]
Bueno, según [Wordreference](http://www.wordreference.com/es/translation.asp?tranword=range), range se traduce como **rango**, en ningún caso como **intervalo**. Sin embargo, mirando el contexto, algunas veces puede traducirse como **intervalo**, **ámbito**, o **campo**, pero yo siempre lo he utilizado como **rango** (desde "rango de edad", "rango medio"...) 

P.D.: Acabo de mirar en la [RAE](http://dle.rae.es/?id=V7xwLhM) y la definición en el contexto de "estado" es el mismo que la definición de **range** por lo que no lo considero mal traducido, ¿no?

**Comment by mirubiri** [comment]
> P.D.: Acabo de mirar en la RAE y la definición en el contexto de "estado" es el mismo que la definición de range por lo que no lo considero mal traducido, ¿no?

No es en concepto de estado. Pone estad. y si dejas el ratón encima te aclara que es un concepto estadístico.

En la rae [intervalo]http://dle.rae.es/?id=LxNMdqS:

2. m. Conjunto de los valores que toma una magnitud entre dos límites dados. Intervalo de temperaturas, de energías, de frecuencias.

De todos modos, estoy viendo que se traduce indistintamente. En el portal lingüístico de Microsoft la primera traducción que sale es "intervalo", pero se puede ver que se ha traducido también como rango...

Creo que en esta ocasión es cuestión de gustos

**Comment by Lynx901** [comment]
Pues como tú gustes, a mí me es indiferente xD

**Comment by mirubiri** [comment]
Pues venga aceptamos rango, que es más corto.

**Comment by mirubiri** [comment]
Cambio el título y cierro
