### ISSUE TITLE
Actualización del libro a Swift 3.0

### ISSUE THREAD

**Issue by mirubiri** [mirubiri/El-Lenguaje-de-Programacion-Swift#2]
En Swift.org han publicado la versión del libro para Swift 3 y veo que no existen muchos cambios. Voy a actualizar el proyecto para incluir los archivos del nuevo libro y generar una traducción automática a partir de las memorias de traducción del libro sobre Swift 2.

**Comment by Lynx901** [comment]
Justo estaba mirando que han sacado la nueva versión del libro pero tiene una etiqueta "Beta" que no sé si va por la versión de Swift o por la versión del libro... De todas maneras me parece una idea genial actualizar cuanto antes.

**Comment by mirubiri** [comment]
Estoy leyendo la documentación de OmegaT para ver como se actualizan correctamente los archivos de origen, pero todavía no me queda claro. Quiero crear un nuevo proyecto con OmegaT que esté preparado para trabajo en grupo, ya que parece ser que OmegaT tiene la capacidad de automatizar todo el workflow con git.

**Comment by Lynx901** [comment]
En eso no puedo ayudar puesto que no conozco OmegaT. He estado curioseando un rato pero no he encontrado nada de cómo hacer todo eso. En cuanto tengas algo avisa para ponernos manos a la obra.

**Comment by mirubiri** [comment]
Actualizado y preparado el proyecto para descarga
