### ISSUE TITLE
[above = anterior, below = siguiente] Cuando se trata de ejemplos

### ISSUE THREAD

**Issue by mirubiri** [mirubiri/El-Lenguaje-de-Programacion-Swift#20]
He visto en muchos sitios las expresiones "example below" "example above", algunas veces los he traducido como "ejemplo siguiente" o "ejemplo anterior". Creo que es más correcto de esta manera, aunque podríamos seguir con la traducción literal y decir "ejemplo superior" y "ejemplo inferior".

El problema que le veo a "superior" e "inferior" es que como estamos traduciendo un libro electrónico, puede que al cambiar de página un ejemplo deje de estar en una posición inferior al párrafo que lo menciona y viceversa. Por ejemplo cuando un párrafo te menciona "el ejemplo inferior" y al pasar de página te lo encuentras en la parte superior de la misma...

**Comment by Lynx901** [comment]
Yo lo traduzco según el día, a veces pongo **siguiente** o **anterior** y otras **superior** o **inferior**, la verdad es que según me venga la traducción a la cabeza en ese momento. Igualmente, a mi parecer es indiferente porque se sobreentiende que **superior** e **inferior** hacen referencia a los ejemplos anteriores y siguientes, pero si prefieres usar siempre **siguiente** y **anterior** por mí no hay ningún problema

**Comment by mirubiri** [comment]
Es solamente por mantener la integridad y utilizar solo una traducción.

**Comment by Lynx901** [comment]
Pues **siguiente** y **anterior** entonces 😁
