### ISSUE TITLE
Lenguaje formal o informal (tu o usted)

### ISSUE THREAD

**Issue by mirubiri** [mirubiri/El-Lenguaje-de-Programacion-Swift#3]
He visto que los textos traducidos de Apple utilizan casi siempre un lenguaje formal (you = usted). Creo que deberíamos adaptar los textos traducidos al lenguaje formal y continuar utilizándolo en los subsiguientes.

**Comment by Lynx901** [comment]
Si, yo también me he fijado alguna vez en eso y me parece buena idea.

**Comment by mirubiri** [comment]
Cierro
