### ISSUE TITLE
Nuevo en OmegaT

### ISSUE THREAD

**Issue by Lynx901** [mirubiri/El-Lenguaje-de-Programacion-Swift#4]
He comenzado a traducir algunos párrafos y he dado un "commit" pero no estoy seguro de si estoy usando bien OmegaT y tal, ¿podrías confirmármelo? Gracias.

**Comment by mirubiri** [comment]
En realidad has hecho 4. OmegaT por defecto envía los cambios cada 3 minutos, es una opción que se puede configurar. Ten en cuenta que tienes que incluir todas las etiquetas en los textos que traduzcas con el mismo contenido que hay entre ellas (si te dejas algunas, OmegaT tiene una opción para verificar las que faltan). Las etiquetas son las que aparecen en la forma <a1>...<a1>.

**Comment by Lynx901** [comment]
Vale, lo de las etiquetas creo que sí estoy lo estoy haciendo (realmente no estoy seguro, solo estoy cambiando el inglés por el español y ya está), y lo de los minutos ya lo he subido a 15 para que no se actualice cada vez que cambie una letra...

**Comment by Lynx901** [comment]
¿Los porcentajes de traducción del README del proyecto son correctos? Por ejemplo en "A Swift Tour" (archivo GuidedTour.xhtml) la tabla dice que está al 100% pero en OmegaT me salen muy pocas partes traducidas.

**Comment by mirubiri** [comment]
Eran correctos hasta la actualización. Hubo un problema con los primeros capítulos cuando estaba aprendiendo a utilizar Omega e imagino que ahora ha salido... Ya no puede volver a suceder por la configuración del proyecto, pero si, habría que revisarlos.

**Comment by mirubiri** [comment]
Cierro
