### ISSUE TITLE
Traducción de términos

### ISSUE THREAD

**Issue by Lynx901** [mirubiri/El-Lenguaje-de-Programacion-Swift#5]
¿Qué traducción debería tener el término "Playground"? En español sería algo así como campo de juego, o campo de trabajo (porque poner "patio" o "recreo" queda bastante mal)... Mi propuesta es no traducirlo y dejarlo como Playground, pero no sé.

**Comment by Lynx901** [comment]
Aprovechando, ¿la palabra "string" cómo debería traducirse? En mi día a día utilizo string como tal, aunque en la carrera utilizan "cadena de caracteres".

**Comment by mirubiri** [comment]
Yo mantendría Playground, ya que XCode no está traducido y no queremos confundir a la gente cuando vaya a buscar esa funcionalidad. Si algún día Apple traduce XCode ya veremos.

Sobre los términos String, Array, Set... creo que lo mejor será traducirlos sólo cuando intentan explicar el término en si o algo relacionado con el mismo, por ejemplo:

__"An String represent a chain of characters" = "Una cadena de carácteres representa una cadena de carácteres".__

Esto no explica nada, en cambio traducirlo como "Un String representa una cadena de carácteres" es mas explicativo en Español.

Una anotación. Cuando queramos hablar sobre términos es mejor que abramos un "issue" para cada término, así los podemos discutir de forma individual ahora y más adelante y los podemos encontrar con facilidad en la lista de "issues"

**Comment by mirubiri** [comment]
Por ejemplo, este caso en vez de titularse "Traducción de términos" deberíamos haberlo dividido en 2, titular a cada uno por su nombre "Playground" y "String". En caso de que hablemos de una norma comun para traducir términos relacionados podemos referírnos a ellos como "Tipos Básicos (String, Array...)". ¿Qué te parece?

**Comment by Lynx901** [comment]
Me parece perfecto, más que nada lo he hecho por no saturarlo todo de issues, pero es verdad que será mucho más ordenado y más susceptible a futuras aportaciones. Genial.

**Comment by mirubiri** [comment]
No te preocupes por el número de issues, no es importante. Es más importante que cada uno esté dedicado a un solo asunto concreto. Esto es parecido al principio de responsabilidad simple en programación. 😉

**Comment by mirubiri** [comment]
Cierro
