### ISSUE TITLE
Angle Brackets = ángulos

### ISSUE THREAD

**Issue by Lynx901** [mirubiri/El-Lenguaje-de-Programacion-Swift#6]
En inglés está claro lo que es, pero en castellano, llamarlos paréntesis angulares, llaves angulares, o similares es muy raro y no se reconoce... Yo lo llamaría cuña, pues he estado buscando y en la [página de "Paréntesis" de Wikipedia](https://www.wikiwand.com/es/Par%C3%A9ntesis) lo llaman cuñas. ¿Qué opinas?

**Comment by mirubiri** [comment]
Según [Microsoft Language Portal](https://www.microsoft.com/Language/en-US/Search.aspx?sString=angle+brackets&langID=es-es) lo traducen como __corchetes o paréntesis angulares__

En Español según la RAE se traduciría como __símbolos de mayor y menor__. 

He visto por internet que también los llaman __cuñas__, __corchángulos__ ,  __ángulos__ y __escuadras__

Podemos consultar otras fuentes o algún libro de programación de Java 6+ en Español que es cuando introdujeron la notación Array<class> para ver como los han traducido.

A mi la que mejor me suena -en caso de querer utilizar una expresión corta- es __ángulos__ ...

**Comment by Lynx901** [comment]
En la Fundación Mozilla, en el "curso" de javascript lo llaman también **cuñas** o **ángulos**. Me parece más apropiado ángulos que cuñas puesto que es más descriptivo.

**Comment by mirubiri** [comment]
Adjudicado!, ángulos entonces. Cambio el título para reflejar la traducción y cierro.

Creo que estas cosas deberíamos añadirlas al glosario, no se si OmegaT lo actualiza automáticamente en GitHub o habría que subirlo a mano.
