### ISSUE TITLE
AboutSwift.xhtml <Segment 0110>

### ISSUE THREAD

**Issue by mirubiri** [mirubiri/El-Lenguaje-de-Programacion-Swift#7]
> Daniel modificó por última vez la traducción el 17-jun-2016 a las 20:01:42
> It’s designed to scale from “hello, world” to an entire operating system.
> Está diseñado en escala desde el "hola, mundo" a un sistema operativo completo.

Hay que tener un poco más de cuidado con las traducciones, aquí has cambiado el significado de la frase y no se entiende. La traducción correcta sería:

"Está diseñado para escalar desde un "hello,world!", hasta un sistema operativo completo"

En esa frase está hablando de la capacidad de Swift a la hora de abordar desarrollos que requieran una gran cantidad de proceso o una gran carga de trabajo.

**Comment by Lynx901** [comment]
Cierto, la entendí bien pero no supe traducirlo correctamente. Mis disculpas 😅

**Comment by mirubiri** [comment]
Tenemos que ver como hacemos uso del glosario de OmegaT y de las traducciones alternativas, para ver los cambios, no se si ahora se reflejan.

**Comment by Lynx901** [comment]
El glosario a mí al menos me marca muy pocas palabras, tales como "values" o "Swift" que no tienen una traducción muy difícil al fin y al cabo, y las traducciones alternativas directamente me aparecen vacías en todas las ocasiones, no sé si es que lo tendré mal configurado o que realmente no hay ninguna.

**Comment by mirubiri** [comment]
Puedes añadir términnos al glosario fácilmente, al fin y al cabo no es mas que un archivo de texto, incluso puedes hacerlo desde el propio OmegaT.

Traducciones alternativas no hay, por que hasta ahora estaba trabajando yo solo y no he hecho uso de ellas.

**Comment by Lynx901** [comment]
Cuando hago commits se hacen de dos en dos, uno con la traducción y otro que dice "Added glosaryitem(s)" cuando en realidad no he añadido nada al glosario, ¿puede ser que OmegaT detecte automáticamente algunas palabras esenciales y las añada? 

A partir de ahora usaré mucho más el glosario añadiendo más cosas porque ya me ha pasado de traducir una misma palabra de dos formas diferentes y darme cuenta más tarde de ello y tener que volver a cambiarlo xD

**Comment by mirubiri** [comment]
Creo recordar que no añade nada al glosario, pero si, el glosario es útil para no traducir las palabras de formas diferentes y mantener cierta integridad en la traducción.

Por cierto, cuando veas una palabra en ingles como "familiar" o "support" y te veas traduciéndola al español con palabras muy parecidos -como "familiar" o "soporte" en este caso- sospecha y búscalas en el diccionario, muy a menudo son "barbarismos" que tienen una traducción mejor. Yo ya he hecho alguna traducción así y me he dado cabezazos contra la pared intentando hacerla encajar por no buscarla previamente xD

**Comment by Lynx901** [comment]
Si, me pasó con "friendly" por ejemplo, aunque hay palabras como "familiar" que en inglés y en español tienen un significado muy muy parecido y una vez que lees la frase en inglés es complicado encajar un sinónimo o similares en español xDD Aún así siempre traduzco con el diccionario al lado porque hay palabras que en inglés entiendo pero en español no acierto a traducirlas.

**Comment by mirubiri** [comment]
cierro
