### ISSUE TITLE
"Remainder Operator"

### ISSUE THREAD

**Issue by Lynx901** [mirubiri/El-Lenguaje-de-Programacion-Swift#8]
He visto que has traducido "remainder operator" como "operador resto", pero para la operación como tal has usado el término "resta". Creo que es mejor llamarlo "operador resta" u "operador de resta" para que existe integridad entre los tipos de operadores ("operador de suma", "operador de multiplicación", etc.) ¿Qué opinas?

**Comment by mirubiri** [comment]
Indícame los segmentos o lugares donde están esas traducciones, sin ver el contexto no se que responderte.

**Comment by Lynx901** [comment]
En "BasicOperators.xhtml", cada uno de los operadores tiene un apartado dedicado.

**Comment by mirubiri** [comment]
"Operador resto" -> 4 % 2 = 0
"Operador resta" -> 4 - 2 = 2

Son cosas distintas, no se le puede cambiar el nombre. ¿Te refieres a eso?

**Comment by Lynx901** [comment]
Oh, cierto, mea culpa. No leí todo el contexto y pensé que se refería a la resta 😅

**Comment by mirubiri** [comment]
Ah!, solucionado entonces, lo cierro!. :wink:
