### ISSUE TITLE
"Unary Plus Operator" = "Operador unario más"

### ISSUE THREAD

**Issue by Lynx901** [mirubiri/El-Lenguaje-de-Programacion-Swift#9]
Al igual que con el "operador resto", creo que si "unary minus operator" = **operador unario menos**, entonces "unary plus operator" debería ser **operador unario más** en lugar de **operador unario suma** puesto que su función no es _sumar_ si no _poner en positivo_ , no sé si me explico.

**Comment by mirubiri** [comment]
Aquí me ocurre lo mismo, indícame el segmento o pega las frases donde está el asunto. Hay veces que no estoy delante del ordenador y con esa información no te puedo responder. :\

**Comment by Lynx901** [comment]
![image](https://cloud.githubusercontent.com/assets/9676003/16177247/8628bd90-3626-11e6-9aa5-4c096830ba4e.png)
En esta zona, aunque el apartado del "unary plus operator" no está traducido, el título sí lo estaba, con lo que el resto de términos están ligados a esto.

**Comment by mirubiri** [comment]
Si, debería ser "Operador unario más" para mantener la coherencia.
